test:
  api_host: http://framey.com
  run_env: production
  api_key: 0RNOGIZDJJJFMVK7KREBLNGLJ
  secret: 3ACOPFHGXOTOXLJZ8VP3YQUC5

development: 
  api_host: http://framey.com
  run_env: production
  api_key: 0RNOGIZDJJJFMVK7KREBLNGLJ
  secret: 3ACOPFHGXOTOXLJZ8VP3YQUC5  


staging:
  api_host: http://framey.com
  run_env: production
  api_key: 0RNOGIZDJJJFMVK7KREBLNGLJ
  secret: 3ACOPFHGXOTOXLJZ8VP3YQUC5
    
production:
  api_host: http://framey.com
  run_env: production
  api_key: KTJQBCMODK2OYHJMNJ1YUW8HT
  secret: RZAIJQFQ8XLROU5F36TG2MUJQ